# Generated by Django 5.0.2 on 2024-02-26 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FirstProject', '0002_profile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ename', models.CharField(max_length=50)),
                ('esalary', models.FloatField(max_length=50)),
                ('eadd', models.CharField(max_length=100)),
            ],
        ),
    ]
